// Application-name to icon-name mapping for workspace and window pills. Keys are
// macOS application names; values are catalog identifiers from
// lib/components/icons/catalog.js. Unknown apps fall back to the default icon.
export const appIcons = {
  Airmail: "airmail",
  Alacritty: "terminal",
  Alfred: "alfred",
  Anki: "anki",
  Antigravity: "antigravity",
  Anytype: "anytype",
  Aqua: "aqua",
  Arc: "arc",
  Atom: "atom",
  Audacity: "audacity",
  Bear: "bear",
  Bitwarden: "bit-warden",
  Blender: "blender",
  Bruno: "bruno",
  Calendar: "calendar",
  Calibre: "book",
  Caprine: "caprine",
  CARROT: "carrot",
  ChatGPT: "chat-gpt",
  Chatterino: "chatterino",
  Chromium: "google-chrome",
  Claude: "claude",
  ClaudeCode: "claude-code",
  ClickUp: "click-up",
  Cline: "cline",
  CLion: "c-lion",
  Code: "code",
  Codex: "codex",
  ComfyUI: "comfy-ui",
  Copilot: "copilot",
  Cursor: "cursor",
  DataGrip: "data-grip",
  Deezer: "deezer",
  Default: "default",
  Discord: "discord",
  Drafts: "drafts",
  Dropbox: "dropbox",
  Element: "element",
  Emacs: "emacs",
  FaceTime: "face-time",
  Fantastical: "calendar",
  Figma: "figma",
  Finder: "finder",
  Firefox: "firefox",
  Fleet: "fleet",
  Folx: "folx",
  FreeTube: "free-tube",
  Ghostty: "ghostty",
  Gnucash: "gnu-cash",
  GoLand: "go-land",
  GoodNotes: "good-notes",
  Goose: "goose",
  GrandTotal: "dollar",
  Helium: "helium",
  HEY: "mail",
  HTTPie: "htt-pie",
  Hyper: "terminal",
  Insomnia: "insomnia",
  Iris: "iris",
  iTerm2: "terminal",
  Joplin: "joplin",
  Kakoune: "kakoune",
  Kalender: "calendar",
  KeePassXC: "kee-pass-xc",
  Keynote: "keynote",
  kitty: "terminal",
  LibreWolf: "libre-wolf",
  Linear: "linear",
  Live: "ableton",
  MacVim: "vim",
  Maestro: "maestro-ai",
  Mail: "mail",
  MailMate: "mail",
  Mailspring: "mail",
  MAMP: "mamp",
  Manus: "manus",
  Matlab: "matlab",
  Mattermost: "mattermost",
  Messages: "messages",
  Mimestream: "mimestream",
  Min: "min-browser",
  Miro: "miro",
  MoneyMoney: "bank",
  mpv: "mpv",
  Music: "music",
  Musik: "music",
  n8n: "n8n",
  Nachrichten: "messages",
  Neovide: "vim",
  NetNewsWire: "net-news-wire",
  Notability: "notability",
  NotebookLM: "notebook-lm",
  Notes: "notes",
  Notion: "notion",
  Nova: "nova",
  Numbers: "numbers",
  OBS: "obs-studio",
  Obsidian: "obsidian",
  Ollama: "ollama",
  OmniFocus: "omni-focus",
  OpenClaw: "open-claw",
  opencode: "opencode",
  OrbStack: "orb-stack",
  Pages: "pages",
  Perplexity: "perplexity",
  PHPStorm: "php-storm",
  Pine: "pine",
  Pins: "pins",
  Plex: "plex",
  Podcasts: "podcasts",
  Postman: "postman",
  Preview: "pdf",
  PyCharm: "py-charm",
  Quip: "quip",
  qutebrowser: "qute-browser",
  Receipts: "dollar",
  Reeder: "reeder5",
  Reminders: "reminders",
  Remnote: "remnote",
  Replit: "replit",
  Rider: "rider",
  Roon: "roon",
  RubyMine: "ruby-mine",
  RustRover: "rust-rover",
  Safari: "safari",
  Screens4: "screens4",
  Setapp: "setapp",
  Signal: "signal",
  sioyek: "pdf",
  Sketch: "sketch",
  SketchUp: "sketch-up",
  Skim: "pdf",
  Skype: "skype",
  Slack: "slack",
  Spark: "spark",
  Spotify: "spotify",
  Spotlight: "spotlight",
  spotube: "spotube",
  Spotube: "spotube",
  TablePlus: "table-plus",
  Tailscale: "tailscale",
  Telegram: "telegram",
  Terminal: "terminal",
  Texts: "messages",
  Things: "things",
  Thunderbird: "thunderbird",
  TickTick: "tick-tick",
  TIDAL: "tidal",
  Todoist: "todoist",
  Tower: "tower",
  Transmit: "transmit",
  Trello: "trello",
  Tweetbot: "twitter",
  Twitter: "twitter",
  Typora: "text",
  Vim: "vim",
  VimR: "vim",
  Vivaldi: "vivaldi",
  VLC: "vlc",
  VSCodium: "vs-codium",
  Warp: "warp",
  WebStorm: "web-storm",
  WezTerm: "terminal",
  WhatsApp: "whats-app",
  Xcode: "xcode",
  zathura: "pdf",
  Zed: "zed",
  Zen: "zen-browser",
  Zeplin: "zeplin",
  Zotero: "zotero",
  Zulip: "zulip",
  "1Password 7": "one-password",
  "1Password": "one-password",
  "Acrobat Reader": "pdf",
  "Activity Monitor": "activity",
  "Affinity Designer": "affinity-designer",
  "Affinity Photo": "affinity-photo",
  "Affinity Publisher": "affinity-publisher",
  "Android Messages": "android-messages",
  "Android Studio": "android-studio",
  "App Store": "app-store",
  "Apple Simulator": "apple-simulator",
  "Bambu Studio": "bambu-studio",
  "Battle.net": "battle-net",
  "Beekeeper Studio": "beekeeper",
  "Brave Browser": "brave-browser",
  "Canary Mail": "mail",
  "CleanMyMac X": "desktop",
  "Code - Insiders": "code",
  "Color Picker": "color-picker",
  "DEVONthink 3": "devo-nthink3",
  "Discord Canary": "discord",
  "Discord PTB": "discord",
  "Docker Desktop": "docker",
  "Evernote Legacy": "evernote-legacy",
  "Figma Beta": "figma",
  "Final Cut Pro": "final-cut-pro",
  "Find My": "radar",
  "Firefox Developer Edition": "firefox-developer-edition",
  "Firefox Nightly": "firefox-developer-edition",
  "GitHub Desktop": "github",
  "Google Chrome Canary": "google-chrome",
  "Google Chrome": "google-chrome",
  "Grammarly Editor": "grammarly",
  "Home Assistant": "home-assistant",
  "IntelliJ IDEA": "idea",
  "Keyboard Maestro": "keyboard-maestro",
  "League of Legends": "league-of-legends",
  "LM Studio": "lm-studio",
  "MAMP PRO": "mamp",
  "Microsoft Edge": "microsoft-edge",
  "Microsoft Excel": "microsoft-excel",
  "Microsoft Outlook": "microsoft-outlook",
  "Microsoft PowerPoint": "microsoft-power-point",
  "Microsoft Teams": "teams",
  "Microsoft To Do": "things",
  "Microsoft Word": "microsoft-word",
  "Monero GUI": "monero-gui",
  "MongoDB Compass": "mongo-db",
  "OBS Studio": "obs-studio",
  "Parallels Desktop": "parallels",
  "Pi-hole Remote": "pihole",
  "PomoDone App": "pomodone",
  "Proton Mail": "proton-mail",
  "Redis Insight": "redis",
  "Remote Desktop": "remote-desktop",
  "Rocket.Chat": "rocket-chat",
  "Royal TSX": "royal-tsx",
  "Safari Technology Preview": "safari",
  "Sequel Ace": "sequel-ace",
  "Sequel Pro": "sequel-pro",
  "Sublime Text": "sublime-text",
  "Super Productivity": "super-productivity",
  "System Preferences": "gear",
  "System Settings": "gear",
  "TeamSpeak 3": "team-speak",
  "Tor Browser": "tor-browser",
  "VMware Fusion": "v-mware-fusion",
  "Windows App": "windows",
  "YouTube Music": "youtube-music",
  "zoom.us": "zoom",
};

const normalize = (name) => (name ?? "").replace(/[\u200E]/g, "");

/** Icon name for a running application, defaulting when unrecognized. */
export function iconForApp(name) {
  return appIcons[normalize(name)] ?? "default";
}
